spring.application.name=firs

# MySQL Connection
spring.datasource.url=jdbc:mysql://localhost:3306/firs?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234
# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# OPTIONAL (only if using templates folder)
# spring.mvc.view.prefix=/templates/
# spring.mvc.view.suffix=.html